export const HANDLE_GET_LIST_USER = "HANDLE_GET_LIST_USER";
export const HANDLE_GET_LIST_USER_SUCCESS = "HANDLE_GET_LIST_USER_SUCCESS";
export const HANDLE_GET_USER_LIST_SUCCESS_DETAIL = "HANDLE_GET_USER_LIST_SUCCESS_DETAIL";

export const HANDLE_ADD_GET_LIST_USER = "HANDLE_ADD_GET_LIST_USER";
export const HANDLE_ADD_GET_LIST_USER_SUCCESS = "HANDLE_ADD_GET_LIST_USER_SUCCESS";
export const HANDLE_ADD_GET_LIST_USER_SUCCESS_DETAIL = "HANDLE_ADD_GET_LIST_USER_SUCCESS_DETAIL";

export const HANDLE_DELETE_GET_LIST_USER = "HANDLE_DELETE_GET_LIST_USER";
export const HANDLE_DELETE_GET_LIST_USER_SUCCESS = "HANDLE_DELETE_GET_LIST_USER_SUCCESS";
export const HANDLE_DELETE_GET_LIST_USER_SUCCESS_DETAIL = "HANDLE_DELETE_GET_LIST_USER_SUCCESS_DETAIL";

export const HANDLE_EDIT_GET_LIST_USER = "HANDLE_EDIT_GET_LIST_USER";
export const HANDLE_EDIT_GET_LIST_USER_SUCCESS = "HANDLE_EDIT_GET_LIST_USER_SUCCESS";
export const HANDLE_EDIT_GET_LIST_USER_SUCCESS_DETAIL = "HANDLE_EDIT_GET_LIST_USER_SUCCESS_DETAIL";
